spring:
    datasource:
      url: jdbc:mysql://39.100.39.63:3306/user_center
      hikari:
        username: root
        password: abc123
        driver-class-name: com.mysql.cj.jdbc.Driver

    cloud:
      nacos:
        discovery:
          # 指定nacos server的地址
          server-addr: localhost:8848
          # 配置namespace
#          namespace: 705f73a7-1692-471e-bc1f-211ee6af9c9e
          # NJ
          cluster-name: BJ

    application:
      # 服务名称尽量使用-，不要使用_，更不要使用特殊字符
      name: user-center

server:
  port: 8081
